jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.1
      - run: dotnet build

  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.1
      - run: dotnet test
  # analyze:
  # package:
  # deploy:

name: cibuild

on:
  push:
    brancher:
      - master


# person:
#   firstName: 'Jordan' # string
#   lastName: 100 # number
#   middleName: true # bool
#   alias: #collection
#     - 'dotnet'
#     - 'lead'
#     - subAlias:
      